config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :todos
  resources :users
  get "/signin" => "sessions#new", as: :new_session
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user

  scope :overdue, -> { where("due_date < ? and completed= ?", Date.today, false) }
  scope :duetoday, -> { where("due_date = ?", Date.today) }
  scope :duelater, -> { where("due_date > ?", Date.today) }
  scope :completed, -> { where(completed: true) }

  validates :todo_text, presence: true, length: { minimum: 2 }
  validates :due_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :todos
  validates :first_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      flash[:alert] = "Please signin to access application"
      redirect_to root_path
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      flash[:notice] = "You have already signed in.."
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    if current_user
      flash[:notice] = "You have already signed in, Signout and signin to other account"
      redirect_to todos_path
    else
      render "new"
    end
  end

  def create
    user = User.find_by(email: params[:email])
    password = params[:password]
    if user && user.authenticate(password)
      session[:current_user_id] = user.id
      redirect_to todos_path
    else
      flash[:alert] = "Incorrect email or password, please try again!"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    flash[:success] = "Successfully logged out..!"
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :find_current_todos

  def index
  end

  def show
    id = params[:id]
    render plain: Todo.find(id).to_pleasant_string
  end

  def create
    @todo = Todo.new(todo_text: params[:todo_text],
                     due_date: params[:due_date],
                     completed: false,
                     user_id: current_user.id)
    if @todo.save
      redirect_to todos_path
    else
      flash[:alert] = @todo.errors.full_messages[0]
      redirect_to todos_path
    end
  end

  def update
    # double bang operator is an aletrnative !!completed
    completed = params[:completed].nil? ? false : true
    @todos.update(params[:id], completed: completed)
    redirect_to todos_path
  end

  def destroy
    todo = @todos.find(params[:id])
    todo.destroy
    redirect_to todos_path
  end

  private

  def find_current_todos
    @todos = current_user.todos
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    if current_user
      flash[:notice] = "You have already signed in ,Signout and signup for another account"
      redirect_to todos_path
    else
      render "new"
    end
  end

  def create
    user = User.new(first_name: params[:first_name],
                    last_name: params[:last_name],
                    email: params[:email],
                    password: params[:password])
    if user.save
      session[:current_user_id] = user.id
      redirect_to todos_path
    else
      flash[:alert] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="home-title">Welcome to my Todo Application</h1>
<h3 class="user-authenticate">
  If you are new user <%= link_to "signup here", new_user_path %>
</h3>
<h3 class="user-authenticate">
  If you are existing user <%= link_to "signin here", new_session_path %>
</h3>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type,msg| %>
  <div class="alert alert-<%= type %>" >
      <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render "layouts/flash_messages" %>
  <% if @current_user %>
    <p class="user-header">
      Welcome <%= @current_user.first_name %>
      <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
    </p>
  <% end %>
  <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="todo-section">
  <div class="title-section">
    <h3 class="due-title"><%= section_title %></h3>
    <div class="task-count"><%= todos.completed.count %>/<%= todos.count %></div>
  </div>
  <div class="todos-list">
    <% todos.each do |todo| %>
        <div class="single-todo">
          <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
            <%= check_box_tag 'completed','todo',todo.completed,class: 'todo-checkbox',onclick: 'this.form.submit()' %>
          <% end %>
          <%= label_tag todo.todo_text,nil,class: "todo-item #{todo.completed ? "todo-complete" : ""}" %>
          <% if show_duedate %>
            <span class="due-date"><%= todo.due_date.to_s(:short) %></span>
          <% end %>
          <a href="javasrcipt:void(0)">
            <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
              <%= image_submit_tag "delete.png", alt: "delete todo" %>
            <% end %>
          </a>
        </div>
    <% end %>
  </div>
</section>

app/views/todos/index.html.erb
<div class="container">
  <div class="content">
    <h2 class="todo-title">My To-do List</h2>

    <%= form_with(url: "/todos",method: "post",class: "form-content" ) do %>
        <%= text_field_tag 'todo_text',nil,placeholder: 'Whats next?',class: 'text-holder' %>
        <%= date_field_tag 'due_date',nil,class: 'date-holder' %>
        <%= submit_tag 'Add', class: 'btn-1' %>
    <% end %>

    <article class="todo-content">
      <%= render partial: "todo-section", locals: {
        section_title: "Overdue",
        todos: @todos.overdue,
        show_duedate: true
      } %>

      <%= render partial: "todo-section", locals: {
        section_title: "Due Today",
        todos: @todos.duetoday,
        show_duedate: false
      } %>

      <%= render partial: "todo-section", locals: {
        section_title: "Due Later",
        todos: @todos.duelater,
        show_duedate: true
      } %>
    </article>
  </div>
</div>

app/views/users/new.html.erb
<section class="signup-section">
  <h2 class="form-title">Welcome User!</h2>
  <%= form_with url: users_path , method: "post" , class: "user-from" do %>
    <div class="form-element">
      <p class="form-label">First Name :</p>
      <%= text_field_tag "first_name",nil,class: "input-item" %>
    </div>
    <div class="form-element">
      <p class="form-label">Last Name :</p>
      <%= text_field_tag "last_name",nil,class: "input-item" %>
    </div>
    <div class="form-element">
      <p class="form-label">Email :</p>
      <%= email_field_tag "email",nil,class: "input-item" %>
    </div>
    <div class="form-element">
      <p class="form-label">Password :</p>
      <%= password_field_tag "password",nil,class: "input-item" %>
    </div>
    <div class="form-element">
      <%= submit_tag "SignUp!", class: "form-button" %>
    </div>
  <% end %>
</section>